language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11

script: mvn clean install

addons:
  chrome: stable

script:
  - chrome --no-sandbox

cache:
  directories:
    - node_modules

before_install:
  - chmod +x mvnw

after_success:
  - mvn clean test jacoco:report coveralls:report