language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk11

branches:
  only:
    - master

addons:
  chrome: stable

script:
  - mvn clean install

cache:
  directories:
    - node_modules

before_install:
  - chmod +x mvnw